### ISSUE TITLE
Call to undefined function codepackniter()

### ISSUE THREAD

**Issue by arvind-007** [mjangir/codepackniter#2]
Got above issue on refreshing page after installing all dependency and compilation.

**Comment by mjangir** [comment]
Did it create the codepackniter helper file in helpers?

**Comment by arvind-007** [comment]
Yes, It is there but codepackiniter helper is not loaded in autoload config. undefined issue resolved after adding codepackniter in autoload.php.

**Comment by arvind-007** [comment]
/*
| -------------------------------------------------------------------
| Auto-load Helper Files
| -------------------------------------------------------------------
| Prototype:
|
|	$autoload['helper'] = array('url', 'file', 'url', 'codepackniter');
*/
$autoload['helper'] = array();

**Comment by arvind-007** [comment]
codepackniter helper is not loading by default. It is there in comment section, must be in helper array

> /*
| -------------------------------------------------------------------
|  Auto-load Helper Files
| -------------------------------------------------------------------
| Prototype:
|
|	$autoload['helper'] = array('url', 'file', 'url', 'codepackniter');
*/
$autoload['helper'] = array('url', 'file', 'url', 'codepackniter');

**Comment by arvind-007** [comment]
codepackniter helper is not loading by default. It is there in comment section, must be in helper array
> 
/*
| -------------------------------------------------------------------
|  Auto-load Helper Files
| -------------------------------------------------------------------
| Prototype:
|
|	$autoload['helper'] = array('url', 'file', 'url', 'codepackniter');
*/
$autoload['helper'] = array('url', 'file', 'url', 'codepackniter');

**Comment by arvind-007** [comment]
codepackniter helper is not loading by default. It is there in comment section, must be in helper array.
`/*
| -------------------------------------------------------------------
|  Auto-load Helper Files
| -------------------------------------------------------------------
| Prototype:
|
|	$autoload['helper'] = array('url', 'file', 'url', 'codepackniter');
*/
$autoload['helper'] = array('url', 'file', 'url', 'codepackniter');`

**Comment by arvind-007** [comment]
> 
/*
| -------------------------------------------------------------------
|  Auto-load Helper Files
| -------------------------------------------------------------------
| Prototype:
|
|	$autoload['helper'] = array('url', 'file', 'url', 'codepackniter');
*/
$autoload['helper'] = array('url', 'file', 'url', 'codepackniter');

**Comment by jmikerq** [comment]
codepackniter calls base_url(), so also need to add 'url' as helper in autoload.php. otherwise there is exception regarding the undefined method base_url()
